### PR TITLE
Parallelization and bug fixes

### PR DESCRIPTION
**Pull request by jstupak**
Added a few fixes which are needed to run test 4 modules in parallel with pXar (mostly sleep statements).  Also made a few bug fixes, which I think address issues #11 and #9 by @xerxes1986.

### CODE REVIEW

**Comment by jstupak** [comment]
@veloxid What do you think about this PR?

**Comment by veloxid** [comment]
Sorry, I was on a test beam, I will have a look tomorrow.

**Comment by veloxid** [comment]
@jstupak 
Thanks for the commit: 
It is more or less impossible to see which  changes you made within the keithleyClient since you did a lot of formating (whitspace) changes. I do not have any problems with formating changes, but put them in another PR. 
- There are some lines were you added a simicolon at the end of the line. this is not needed in python.
  Please remove them.
- Some remarks to the keithleyClient: 
  - You also removed the leakage current measurements. This is needed and cannot be removed. Is there any reason why you did that?
  - you replaced the read fucntion by a new read function, what is the intention of that?
  - You added a self to the  staticmethods: this does not really make sense...
  - Could you explain the new compliance abort level?
  - We should add an option to the KeithleyInterface to define the commandEndCharacters within the config files.
- Some remarks to psi_agente:
  - We do not have any issues with the delays we set in the past. Could explain why set extension of this delays is needed? What is happening with this short delays?
- jumo_coolingbox.py: 
  - I agre that we have to adjust this lines, but line 220 is no change at all, the added check is already checked before. 
    line 216: Yes we have to add this, I would suggest to do this by
    if temp - self.setpoint > self.deltaT_Max:
    One does not need a check with abs().

**Comment by jstupak** [comment]
I think I should have issued the PR wrt your keithley branch to make my changes more clear.  I will submit this now, and add some comments there

**Comment by veloxid** [comment]
Hi I am not sure wheather you want to have this one merged?
Cheers
Felix

**Pull request merged**
